### ISSUE TITLE
Not working with android studio 2.2 

### ISSUE THREAD

**Issue by trinitron01** [Archinamon/GradleAspectJ-Android#20]
When using the latest stable Android Studio 2.2 with gradle plugin 2.2.0 compilation fails with the following error :

`Error:Cause: com.android.build.gradle.AppPlugin cannot be cast to groovy.lang.GroovyObject`

**Comment by renaudcerrato** [comment]
Another issue here:

```
Error:Unable to load class 'com.android.builder.signing.SignedJarBuilder$IZipEntryFilter'.
Possible causes for this unexpected error include:<ul><li>Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
<a href="syncProject">Re-download dependencies and sync project (requires network)</a></li><li>The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
<a href="stopGradleDaemons">Stop Gradle build processes (requires restart)</a></li><li>Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.</li></ul>In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.
```

**Comment by Archinamon** [comment]
Will be able to look around this issue in first dates of October.

**Comment by renaudcerrato** [comment]
Hi Edgar ! Did you had a look to it yet? 

Best!

**Comment by renaudcerrato** [comment]
any update? Shall we consider the development as stopped and move forward? Migrating to Gradle plugin 2.2 is highly wanted because of the [built-in apt processor](http://www.littlerobots.nl/blog/Whats-next-for-android-apt/)

**Comment by StrLght** [comment]
Hey everyone.

Fixed this issue, for more information you can check out request #21.
If you want fix right now, I created [branch](https://github.com/StrLght/GradleAspectJ-Android/tree/gradle-2.2-artifact) with updated artifact.

**Comment by renaudcerrato** [comment]
Thanks! Will wait for the official release.

**Comment by Archinamon** [comment]
Wow. Good to see somebody else commits :)
Sorry for my absence, I was too busy :(
Will look PR today. Also, does anyone has issues with 2.+ plugin and multidex? On my proj I've got misterious crash with invalid bytecode error, hehe.

**Comment by trinitron01** [comment]
I am still having an error when using the latest version (using gradle 2.2.1 and aspectj 2.0.2, android studio 2.2.1) :

`Error:Unable to load class 'com.android.builder.signing.SignedJarBuilder$IZipEntryFilter'.
Possible causes for this unexpected error include:<ul><li>Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
<a href="syncProject">Re-download dependencies and sync project (requires network)</a></li><li>The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
<a href="stopGradleDaemons">Stop Gradle build processes (requires restart)</a></li><li>Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.</li></ul>In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.`

**Comment by StrLght** [comment]
This is fixed in AspectJ plugin 2.0.3, update your dependency and it should be fine😀

**Comment by Archinamon** [comment]
I faced a problem with transformer, so dunno will it work properly yet) Hope, I'll finish it today :) You can try 2.0.3 yeah, thanks to @StrLght!

**Comment by trinitron01** [comment]
Yeah thanks, exactly, that fixed that, however as @Archinamon mentioned there are still issues with compiling a multidex project with gradle 2+ plugin..

`Execution failed for task ':app:transformClassesWithExtractJarsForDebug'.`
